package HomeTest.car4.enums;

public enum Option {
    NAVIGATION,
    SUNROOF,
    LEATHER_SEATS,
    PARK_ASSIST,
    HEATED_SEATS,
    PARKING_ASSIST,
    MAGNITOLA,
    CRUISE_CONTROL,
    LEATHER_INTERIOR, PARKING_SENSORS, AUTOMATIC_PARKING, BACKUP_CAMERA
}
